### ISSUE TITLE
Hard code date

### ISSUE THREAD

**Issue by Regno** [jasenhuang/smtp#2]
Each sending message have the same created date: 16.09.2015

I suppose that issue is placed in function "buildMIME" at row:
`[mime appendFormat:@"Date: %@\r\n", @"Date: Wed, 16 Sep 2015 15:57:09 +0800"];`

I sugest a solution should be like this:
`[mime appendFormat:@"Date: %@\r\n", [NSDate dateWithTimeIntervalSinceNow:0]];`

**Comment by jasenhuang** [comment]
oh , it's a fool mistake, fixed already.
